name = "ClusteringProject"
uuid = "e175e903-0bec-4a8c-ac13-a88e5639c2ca"
version = "0.1.0"

[deps]
Clustering = "aaaa29a8-35af-508c-8bc3-b662a17a0fe5"
ColorTypes = "3da002f7-5984-5a60-b8a6-cbb66c0b333f"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
GraphRecipes = "bd48cda9-67a9-57be-86fa-5b3c104eda73"
Hungarian = "e91730f6-4275-51fb-a7a0-7064cfbd3b39"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LogExpFunctions = "2ab3a3ac-af41-5b50-aa03-7779005ae688"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"

[compat]
Clustering = "0.15.8"
ColorTypes = "0.11.5"
DataStructures = "0.19.3"
Distances = "0.10.12"
Distributions = "0.25.122"
GraphRecipes = "0.5.15"
Hungarian = "0.7.0"
LinearAlgebra = "1.11.0"
LogExpFunctions = "0.3.29"
Plots = "1.41.1"
SpecialFunctions = "2.6.1"
Statistics = "1.11.1"
StatsBase = "0.34.8"
StatsPlots = "0.15.8"
